export enum RomanticMediterraneanColors {
    MEDITERRANEAN_SKY_BLUE = '#6EA4D2',
    LIGHT_COASTAL_BLUE = '#8B9DC5',
    SOFT_SEAFOAM_BLUE = '#9BCCDD',
    PALE_COASTAL_GRAY_BLUE = '#BCC6DF',
    LAVENDER_MIST = '#E9E7F5',
    SEASHELL_PALE_GREEN = '#D9E8E3',
    SUN_KISSED_LEMON_GREEN = '#D9E59B',
    BUTTERCREAM_YELLOW = '#F5F0C6',
    PEARLY_SEASHELL_BLUE = '#D9E8E5',
    DEEP_AQUA_BLUE = '#6BBCCF',
    COASTAL_CLOUD_BLUE = '#C2D4E0',
    MISTY_COASTAL_BLUE = '#A7BDD5',
    LIGHT_OCEAN_GRAY = '#D0DDE3',
    SUMMER_WHITE = '#F9F9F1',
    COASTAL_STONE_GRAY = '#7388A3'
}