export enum VintageColors {
    SOFT_PEACH = '#FCE0C8',
    DEEP_BROWN_RED = '#7A4438',
    LIGHT_BEIGE_TAN = '#F0D8BE',
    WARM_BEIGE = '#CCB89F',
    MID_BEIGE = '#D4C0A7',
    SANDY_BEIGE = '#F1DAB8',
    BRONZE_BROWN = '#B38A6C',
    PALE_BEIGE = '#F2E1CD',
    LIGHT_PEACH_BEIGE = '#F4E2CE',
    CREAMY_PEACH = '#FCEEE3',
    PALE_PINKISH_BEIGE = '#F0EAEA',
    ROSE_PEACH = '#F1D7C8',
    PINKISH_GRAY_BEIGE = '#DBCAC3',
    OFF_WHITE_YELLOW = '#F7F7EF',
    RUSTY_BROWN = '#B69C8B'
}